# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.8.0
tutorial: false


countries: ["TN"]

enable:
  retrieve_databundle: false # already downloaded
  retrieve_databundle_sector: false
  retrieve_cutout: false # already downloaded
  build_natura_raster: false # imported natura 2000 from databundle
  build_cutout: false # we are using the cutout from the databundle, which is already built
  progress_bar: false

scenario:
  clusters: [5] #small country, few nodes
  opts: [Co2L0.6-4H] # CO₂ limit at 60% base value, 4h time resolution 
  year_prediction: 2040
  
snapshots: # weather profile used, must meet cutout
  start: "2013-01-01"
  end: "2014-01-01"
  

load_options: 
  ssp: "ssp2-2.6" # socioeconomic pathway 2.6 W/m² radiative, middle of the road-for demand scaling and energy traansition
  weather_year: 2013   # wind and solar profiles, must meet cutout
  year_prediction: 2040   # target year for demand: ./data/ssp2-2.6/2040/era5_2013/Africa.csv
  

clean_osm_data_options:
  threshold_voltage: 35000 # only transmission lines relevant to the project, no local

base_network: # coeherent with osm filter above, for both substation and voltage rebasing
  min_voltage_substation_offshore: 35000
  min_voltage_rebase_voltage: 35000

costs:
  year: 2040           # load resources/costs_2040_elec.csv             
  technology_data_version: "v0.13.2" # coherent with config.default.yaml

electricity:
  co2base: 3.218e+7
  automatic_emission: true
  extendable_carriers:
    Generator: [solar, onwind]
    StorageUnit: [battery]
    Link: []
    Line: []
  estimate_renewable_capacities:
    stats: irena
    year: 2020   # 2020 IRENA data is more complete for TN than 2013
    p_nom_min: 0.5
    p_nom_max: false # compute upper limit ?? > usually false 
  

atlite:
  default: cutout-2013-era5
  cutouts:
    cutout-2013-era5:
      module: era5
      time: ["2013-01-01", "2014-01-01"]  # only time, no spatial override
  
renewable:
  hydro:
    hydrobasins_level: 4
    hydro_max_hours: "energy_capacity_totals_by_country"
    cutout: cutout-2013-era5
    resource:
      method: hydro
    extendable: true # real situation: false, hydro potential is very low
  solar:
    cutout: cutout-2013-era5
    resource:
      method: pv
      panel: CSi
      orientation: latitude_optimal
      #https://www.greenbuildingafrica.co.za/a-turning-point-for-algerian-solar/ 
    capacity_per_sqkm: 4.6 #max allowed py pypsa-earth
    correction_factor: 0.854337
    clip_p_max_pu: 1.e-2
    extendable: true
  onwind:
    cutout: cutout-2013-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3
    # correction factor :0.93 
    clip_p_max_pu: 1.e-2
    extendable: true
  offwind-ac:
    cutout: cutout-2013-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3
    # correction factor :0.93 
    clip_p_max_pu: 1.e-2
    extendable: false  # No offshore wind ambition in current TN plans
  offwind-dc:
    cutout: cutout-2013-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3
    # correction factor :0.93 
    clip_p_max_pu: 1.e-2
    extendable: false

solving:
  solver:
    name: highs
    options: highs-default
